package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.subsystems.Drivetrain;

public class TwoPointTurn extends SequentialCommandGroup{
    
    public TwoPointTurn(Drivetrain drivetrain, double leftWheelArcLength, double rightWheelArcLength){
        addCommands(
            new DriveArc(0.2, 0, rightWheelArcLength, drivetrain),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
            new DriveArc(-0.2, leftWheelArcLength, 0, drivetrain)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        );
    }
}
